[tool.poetry]
name = "minioraclev1-0"
version = "0.1.0"
description = ""
authors = ["kian19955 <kiansharifi84@gmail.com>"]
readme = "README.md"
packages = [{include = "minioraclev1"}]

[tool.poetry.dependencies]
python = "^3.12"
scikit-learn = "^1.6.0"
scipy = "^1.14.1"
pandas = "^2.2.3"
numpy = "^2.2.1"
yagmail = "^0.15.293"
matplotlib = "^3.10.0"
deap = "^1.4.2"
pandas-ta = "^0.3.14b0"
mplfinance = "^0.12.10b0"
backtesting = "^0.5.0"
rich = "^13.9.4"
mplcursors = "^0.6"
python-binance = "^1.0.27"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
